# Exercícios NumPy  

#### Importe NumPy como np

In [1]:
import numpy as np

#### Crie uma matriz de zeros

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### Crie uma matriz de ones

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### Crie um array de inteiros de 1 até 100

In [5]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Crie um array dos numeros pares de 2 até 100

In [7]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#### Criei uma matriz 4x4 com valores variando de 0 até 15

In [8]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Crie uma matriz identidade 3x3

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Crie uma matriz de números inteiros

In [12]:
np.arange(2,101,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

#### Crie um array de tamanho 10 igualmente espaçado entre 0 e 20.

In [13]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## Indexação e Seleção

Dada a matriz:

In [14]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Reproduza as saídas das linhas abaixo.

Cuidado ao tentar reproduzir os resultados na mesma linha pois a execução substituirá o resultado previsto.

In [15]:
arr[0]

array([1, 2, 3, 4])

In [16]:
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr[2:4, 1:]

array([[10, 11, 12],
       [14, 15, 16]])

In [18]:
arr[2:4, 2:4]

array([[11, 12],
       [15, 16]])

In [19]:
arr[2:3,2:3:3]

array([[11]])

### Utilizando a mesma matriz dos exercícios acima, obtenha os valores abaixo:

#### Máximo

In [20]:
np.max(arr)

16

#### Desvio padrão

In [21]:
np.std(arr)

4.6097722286464435

### Desafios

#### Some todos os valores

In [22]:
np.sum(arr)

136

#### Obtenha a soma por coluna

In [28]:
arr.sum(axis = 1)

array([10, 26, 42, 58])