In [1]:
import numpy as np

In [2]:
arr = np.arange(0,20)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
arr[5]

5

In [5]:
arr[4:6]

array([4, 5])

In [6]:
arr[2:6] = 20

In [7]:
arr

array([ 0,  1, 20, 20, 20, 20,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
arr = np.arange(0,10)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
slice = arr[2:8]

In [11]:
slice

array([2, 3, 4, 5, 6, 7])

In [12]:
slice[:] = 150

In [13]:
slice

array([150, 150, 150, 150, 150, 150])

In [14]:
arr

array([  0,   1, 150, 150, 150, 150, 150, 150,   8,   9])

In [16]:
slice_copy = arr.copy()

In [17]:
slice_copy

array([  0,   1, 150, 150, 150, 150, 150, 150,   8,   9])

In [18]:
slice_copy[:] = 200

In [19]:
slice_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [20]:
arr

array([  0,   1, 150, 150, 150, 150, 150, 150,   8,   9])

## Arrays 2d

In [21]:
arr2d = ([1,2,3],[4,5,6],[7,8,9,])

In [22]:
arr2d

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [23]:
arr2d[0]

[1, 2, 3]

In [25]:
arr2d[0][2]

3

In [26]:
arr2d = np.array(([1,2,3],[4,5,6],[7,8,9,]))

In [27]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d[:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2d[:2,0:1]

array([[1],
       [4]])

In [31]:
arr2d > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [32]:
bool = arr2d > 2

In [33]:
bool

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
arr2d[bool]

array([3, 4, 5, 6, 7, 8, 9])

In [39]:
array =  np.linspace(0,50,20)

In [40]:
array

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [41]:
array = array.reshape(5,4)

In [42]:
array

array([[ 0.        ,  2.63157895,  5.26315789,  7.89473684],
       [10.52631579, 13.15789474, 15.78947368, 18.42105263],
       [21.05263158, 23.68421053, 26.31578947, 28.94736842],
       [31.57894737, 34.21052632, 36.84210526, 39.47368421],
       [42.10526316, 44.73684211, 47.36842105, 50.        ]])

In [43]:
array[1:3, 2]

array([15.78947368, 26.31578947])