## NumPyArrays

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,]

In [3]:
lista

[1, 2, 3]

In [4]:
type(lista)

list

In [5]:
np.array(lista)

array([1, 2, 3])

In [6]:
a = np.array(lista)

In [7]:
type(a)

numpy.ndarray

In [8]:
lista = [[1,2,3,],[4,5,6,],[7,8,9]]

In [9]:
np.array(lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Arange

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros e uns 

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(2)

array([1., 1.])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [19]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## linspace

In [20]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Rand

In [26]:
np.random.rand(5)

array([0.1801535 , 0.78664598, 0.81451963, 0.99427565, 0.91716365])

In [27]:
np.random.rand(5) * 100

array([81.70930254, 22.21641409, 32.60416967, 54.00645758, 19.8934289 ])

In [30]:
np.random.rand(5,5)

array([[0.9196233 , 0.9858873 , 0.5299299 , 0.29711381, 0.92789311],
       [0.31569532, 0.83263703, 0.66380378, 0.75497848, 0.11133812],
       [0.96687069, 0.00755193, 0.94974942, 0.63676005, 0.0058908 ],
       [0.25254871, 0.2510046 , 0.67205322, 0.29974498, 0.40618121],
       [0.31126304, 0.03559342, 0.16743204, 0.471031  , 0.86391861]])

## Randn

In [29]:
np.random.randn(5)


array([ 1.83855514,  1.86241545,  0.11446841, -1.0795221 ,  1.03604378])

In [31]:
np.random.randn(5,5)

array([[ 0.6631908 ,  0.89729119,  0.35957811, -0.27004   , -0.23407375],
       [-0.60031785, -0.541015  , -0.38258701, -0.45574986, -0.62543835],
       [ 0.87175169,  1.27502821,  0.27602521, -0.83721104, -0.04377324],
       [ 0.10062036,  0.41939736, -0.01343176,  1.40342945,  0.33099679],
       [ 0.11991147,  2.14159987,  0.1594756 ,  1.75042771,  0.51066923]])

## randint

In [34]:
np.random.randint(1,10)

7

In [35]:
np.random.randint(1,100,10)

array([43, 98, 81, 89, 12,  6, 36, 16, 33, 65])

## Reshape

In [36]:
arr = np.random.rand(25)

In [37]:
arr

array([0.50532968, 0.80083959, 0.76392466, 0.87368919, 0.33147027,
       0.31352206, 0.00666417, 0.2699833 , 0.55336192, 0.48238684,
       0.23072744, 0.26500849, 0.80520067, 0.16094199, 0.51088403,
       0.63611452, 0.89963642, 0.35125686, 0.82916477, 0.46866739,
       0.3289712 , 0.8738938 , 0.61801835, 0.469067  , 0.2568666 ])

In [39]:
arr.shape

(25,)

In [40]:
arr

array([0.50532968, 0.80083959, 0.76392466, 0.87368919, 0.33147027,
       0.31352206, 0.00666417, 0.2699833 , 0.55336192, 0.48238684,
       0.23072744, 0.26500849, 0.80520067, 0.16094199, 0.51088403,
       0.63611452, 0.89963642, 0.35125686, 0.82916477, 0.46866739,
       0.3289712 , 0.8738938 , 0.61801835, 0.469067  , 0.2568666 ])

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr

array([[0.50532968, 0.80083959, 0.76392466, 0.87368919, 0.33147027],
       [0.31352206, 0.00666417, 0.2699833 , 0.55336192, 0.48238684],
       [0.23072744, 0.26500849, 0.80520067, 0.16094199, 0.51088403],
       [0.63611452, 0.89963642, 0.35125686, 0.82916477, 0.46866739],
       [0.3289712 , 0.8738938 , 0.61801835, 0.469067  , 0.2568666 ]])

In [43]:
arr.shape

(5, 5)

## max, min, argmax, argmin

In [44]:
arr

array([[0.50532968, 0.80083959, 0.76392466, 0.87368919, 0.33147027],
       [0.31352206, 0.00666417, 0.2699833 , 0.55336192, 0.48238684],
       [0.23072744, 0.26500849, 0.80520067, 0.16094199, 0.51088403],
       [0.63611452, 0.89963642, 0.35125686, 0.82916477, 0.46866739],
       [0.3289712 , 0.8738938 , 0.61801835, 0.469067  , 0.2568666 ]])

In [46]:
arr.max()

0.8996364203805064

In [47]:
arr.min()

0.006664174649496646

In [48]:
arr.argmax()

16

In [50]:
arr.argmin()

6